#!/bin/bash
# NOTE We use Feature Tool ( https://bitbucket.org/ogstudio/feature-tool )
# NOTE to generate different versions from the same source code

dir=`dirname $0`

max_version_id=2

for id in $(seq 1 $max_version_id); do
    version=$id
    echo "Generating version '$version'"
    echo "feature-tool $dir/versions/$version/Features.txt $dir/features"
    feature-tool $dir/versions/$version/Features.txt $dir/features
done

